language: generic

sudo: required
service:
  - docker

before_install:
  - docker build -t wdickerson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wdickerson/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-225743887112"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"